(function(z){
'use strict';var s7=function(a){z.L.call(this);this.aa(a)},c6a=function(a,b){this.user=a;this.quotes=b},d6a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},t7=function(a){return a.TB.best||null},u7=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.mb(b,function(a){return a.mb()},a);return z.qb(b).map(function(a){return new c6a(a[0].cc(),a)},a)},e6a=function(a,b,c,d){return(0,z.id)(a.du[b.name]||
[],function(a){return a.Dd()==c&&a.Ce()==d})},v7=function(){this.AH=1},w7=function(a){z.Hh.call(this);this.aa(a)},f6a=function(a,b){return z.K(a,"slots",b)},g6a=function(a,b){return z.K(a,"requestContext",b)},x7=function(a){z.L.call(this);this.aa(a)},y7=function(a){return z.J(a,"inResponseToMediaResource")},z7=function(a){return z.J(a,"mediumQuote")},h6a=function(a,b){a.JQ=b;return a},A7=function(a,b){return t7(a)?z.UC(t7(a)).filter(function(a){return this.C5(a)==b},a):[]},i6a=function(a,b,c){c=c.ty;
b=b.getAttribute("name").split(" ");var d=z.Lb(b);a=(a.du[c.name]||[]).filter(function(a){return d[a.$i()]});return a.length?z.Iva(a):null},j6a=function(a,b,c,d){b=e6a(a,b,c,d);return u7(a,b)},k6a=function(a,b){var c=0;(a.du[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Me())});return c},l6a=function(a){var b=z.YM(a.pk.Ft,a.pk.$r(),a.um.Ft,a.um.$r()).Ia().trim();0<a.pk.$r()&&(b="…"+b);var c=z.FD(a.yc,a.um.Ft);a.um.$r()<c.Ia().length&&(b+="…");return b},m6a=function(a){var b=z.xB(a.kza),c=a.pk.Ft,
d=c?b.indexOf(c):-1,e=(c=a.um.Ft)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.FD(a.yc,b[d]));b=z.Sa(c);a=z.Dt(c.indexOf(c[0]),a.pk.$r(),c.indexOf(b),a.um.$r(),!1);return z.dka(new z.qt(z.im,z.RDa),c,a,!0)},n6a=function(a,b,c){var d=a.ma.la(z.yDa,{postId:b},{filter:c});return z.rD(a,d,function(){return this.Cb.Rm(d)})},o6a=function(a,b){z.Zs(a,7);var c=new z.Qs("",1,a.Ia());b.forEach(function(a){z.Xs(c,z.Hs(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.Rja(c);for(var d=
z.Sja(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ia().length;z.Xs(a,z.Hs(g,p,l,Object.keys(k)))}}},p6a=function(a,b,c){b="";a.XGa?a=z.n("Top highlight"):(c=""+z.A(z.kP(z.D({H6:!0,$la:!c.useragent.isMobile},a),c)),1==a.Fi&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},B7=function(a,b){this.oi=a;this.Rsa=b;this.Qe=(this.Tk=b=z.sB(a.node,
b))&&b.getAttribute("name");this.tQ=b?z.xw(a,b):-1},C7=function(a){var b=a.length;a=a.match(q6a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},r6a=function(a,b,c){return(0,z.y)(z.WO(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},s6a=function(a,b,c){b="\x3cdiv class\x3d'u-marginLeft10'\x3e\x3cdiv class\x3d\"buttonSet u-inlineBlock\"\x3e"+z.A(z.hk({action:"quote",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Vda())),l:(0,z.N)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),
jc:!0,Wj:!0,tS:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?z.A(z.hk({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.A(z.$da())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",jc:!0,wa:!0},c)):"")+(a.jW?z.A(z.hk({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.A(z.Uj(null))),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",jc:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop11 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+p6a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},D7=function(a){z.km.call(this);var b=z.yn();this.pk=b&&new B7(z.ao(b,!0),a);this.um=b&&new B7(z.ao(b,!1),a)},E7=function(a){z.L.call(this);this.aa(a)},F7=function(a,b){var c=new z.mi(z.hm(b)),c=new z.Xd(c.la(z.BCa)),d=new z.Xd("https://www.facebook.com/v2.7/dialog/share");z.ae(d,z.ue({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},t6a=function(a,b,c){function d(a){return a.replace(/“/g,
"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,"’")}b.content=d(b.content);b.name&&(b.name=d(b.name));var e=String(a(b,null,c)),g=C7(e)-280;0<g&&(b.content=z.ph(b.content,b.content.length-g),e=String(a(b,null,c)));return e},u6a=function(a,b){b=new z.mi(b.authBaseUrl);return new z.Xd(b.Cl(a))},v6a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},w6a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.c8&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?
null:null==a.post.homeCollection.virtuals?null:null==a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({T8:b},a),d=d||{},d=d.T8;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+z.A(z.AO({title:(0,z.N)(""+z.A(z.Nk())),yD:!0,Qg:(0,z.N)(""+
(c.supportsEdit&&d?z.wNa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+z.uNa(z.D({qe:b},a),c)+(b?z.vNa(a,c):"")+z.tNa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},G7=function(a,b,c){z.T.call(this);this.xe=a.get("quotes-data");var d=this.xe.tp;d.subscribe("add",this.Xea,this);d.subscribe("remove",this.Xea,this);this.ib=b;this.Ud=b.pm;this.Am=c;this.wba=[];this.Ja=a.get("app");this.Ga=a.get("popover");this.ma=a.get("route-builder");this.x_=a.get("global-event-bus");this.wza=a.get("progressive-media-loader")},
y6a=function(a,b,c,d){var e=x6a(a,b);if(e){var g=a.ib.isPublished(),k=z.gwa(a.ib);e.jW=g&&k;if(c=z.gG(z.sC(z.rC(z.tC(z.bF(z.uC(a.Ga).jb(s6a,e),z.cF),c),{t6:!0,Ey:!0,Ba:!0}),"popover--quoteAttributions"),d).ua())c.kn("deactivate",function(){this.Gp===b&&H7(this,null)},a),c.po().ba("quote",a.Ota.bind(a,c)).ba("quote-respond",a.Pta.bind(a,c)).ba("twitter",a.Qta.bind(a))}},x6a=function(a,b){if("anon"==b.mb())return{isActive:!1,XGa:!0};var c=I7(a,b),d=b.Dd();b=b.Ce();a=j6a(a.xe,c,d,b);if(!a||!a.length)return null;
a=(0,z.Mb)(a,function(a){return a.user});c=(0,z.id)(a,function(a){return a.userId!=z.Up().userId});return{isActive:(0,z.Qc)(a,function(a){return a.userId==z.Up().userId}),social:c,Fi:a.length}},z6a=function(a,b){a=a.Ud.querySelectorAll('.markup--quote[name~\x3d"'+b.$i()+'"]');return z.bb(a)},I7=function(a,b){b=b.hc()[0].name;return(b=z.ss(a.Ud,b))?a.ib.Zi(b):null},A6a=function(a,b){var c=z.zn(b);return(c=z.CE(a.Am,c))?i6a(a.xe,b,c):null},H7=function(a,b){a.Gp!==b&&(a.Gp&&B6a(a,a.Gp,!1),b&&B6a(a,b,
!0),a.Gp=b)},B6a=function(a,b,c){z6a(a,b).map(function(a){z.od(a,"is-targeted",c)})},J7=function(a,b){(b=C6a(a,b))&&z.AE(a.Bk(),b)},C6a=function(a,b){var c=b.hc(),d=z.ss(a.Ud,c[0].getName());a=z.ss(a.Ud,z.Sa(c).getName());return z.YM(d,b.Dd(),a,b.Ce())},K7=function(a,b,c,d){a={postId:a.ib.Na(),quoteId:b,source:d};z.ux(c?z.Pva:z.bFa,a)},D6a=function(a,b){z.wB(a,z.vB,z.Yb(b,z.Xb(!0)),void 0)},E6a=function(a,b,c){z.ra(a)||(a=a.toString());var d=window,e={scrollbars:!0,OJa:!0,toolbar:!1,location:!0,width:670,
height:690};z.Gb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",OJa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.eia(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();
return d.open(a,b,c)},F6a=function(a){var b=z.Yv(z.Mxa,{THa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Fa(a)}),b.length&&z.hd(a,b))},G6a=function(a){return(0,z.y)(z.A(z.Mk(String(a.content)))+" — "+z.A(z.gs(a))+" "+z.A(a.url))},H6a=function(a,b,c){return(0,z.ji)("https://"+z.Ug(c.textshotHost)+"/image")},I6a=function(a,b,c){return(0,z.ji)("https://twitter.com/"+z.Ug(c.currentUser.twitterScreenName)+"/status/"+z.Ug(a.id))},J6a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+
b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},K6a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+z.A(z.cl({user:a.user,tf:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';
var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.nj(z.D({name:"addCircled",size:"21px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.N)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.hk({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.N)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.N)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.fk({s:d,Uc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.N)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},L6a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},M6a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.ZKa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.O({xb:!0,href:a,s:(0,z.N)(""+e)},c));return(0,z.y)(d)},N6a=function(a,b,c){a=z.n("Tweet must be {$twitterMaxTweetLength} characters or less.",{twitterMaxTweetLength:z.A(c.j.$Ka)});return(0,z.y)(""+a)},O6a=function(a){if(!a)return"";var b=[],c=z.Bb(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},L7=function(a){z.Ww.call(this);this.yc=a.get("dom-model-converter");this.Rda={};this.Jca={};this.u1={};this.qa=a;this.rl=a.get("request");
this.ma=a.get("route-builder");this.Aa=a.get("model-store");this.nb="";this.uea=z.Xl;this.tba=!1;this.Jh=null},M7=function(a,b){var c=a.Rda[b];c||(c=a.Rda[b]=new z.PC,a.za("new_note_list",c,a));return c},P6a=function(a,b){if(!b)return!1;var c=b.Ia();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.Ka(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,a.endIndex=b.index+c,a.content=b[0],!0):!1},N7=function(a,b,c){var d=
b.Na(),e=b.yg(),g=M7(a,b.ge()),k=g?g.indexOf(b):-1,l=b.oy();b.Ts(c);"HIDDEN"==c?a.Aa.remove(b):b=z.pC(a.Aa,b);var p=g?g.indexOf(b):-1;return{Il:a.rl.put(a.ma.la(z.KCa,{postId:d,noteId:e}),{state:c}),DL:function(){b.Ts(l);-1==p&&(-1==k?g.add(b):z.RC(g,b,k))}}},O7=function(a,b,c,d,e,g){var k=z.J(a.Up(c,e),"replies"),l=z.Ta(k,function(a){return a.my()==b}),p=k[l];"HIDDEN"==g&&z.Ya(k,l);c=a.ma.la(z.NCa,{postId:d,noteId:c,replyId:b});a=a.rl.put(c,{state:g});var r=z.Ta(k,function(a){return a.my()==b});
return{Il:a,DL:function(){-1==r&&z.fb(k,l,0,p)}}},Q6a=function(a,b,c){this.range=a;this.anchor=b;this.nC=b.getAttribute("name");this.highlight=c},P7=function(a,b,c){z.T.call(this);this.mAa=b;this.hza=c;this.Oa=a.get("screen");this.bb=a.get("screen-request")},Q7=function(a,b,c,d){z.T.call(this);this.Oa=a.get("screen");this.sp=c;this.nh=d;this.TP=!1;this.gw=this.ih=null;this.Wa(b)},R7=function(){},R6a=function(a){this.sQ=a},S7=function(a,b){return b?z.ss(a.sQ,b):null},S6a=function(a,b,c){D6a(a.sQ,function(a){var e=
a.getAttribute("name");e&&b.call(c,a,e)})},T6a=function(a,b){return z.mg(a.sQ,b)?a.sQ:null},T7=function(a,b,c,d,e){z.VW.call(this,a,b);this.cb(new z.nW(c));this.cb(new z.iX(!1));this.cb(new z.lX(a));this.cb(new z.WW);this.cb(new z.oX(a,!1,!1));this.cb(new z.qX(d,!0));this.ll=!0;this.zm=d;this.rl=a.get("request");this.Fa=a.get("dialog");this.Z0=e;this.ua()},U6a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+
a)},V6a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");return(0,z.y)(""+a)},W6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},X6a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.y)(""+a)},Y6a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},Z6a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},$6a=function(){var a=
z.n("The reply has been deleted.");return(0,z.y)(""+a)},a7a=function(){var a=z.n("Write a note…");return(0,z.y)(""+a)},b7a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},U7=function(a,b,c,d,e){T7.call(this,a,b,e||"Leave a note",400,d||null);this.nb=c;this.ma=a.get("route-builder");this.xf=a.get("notes-data")},V7=function(a,b,c,d,e,g){T7.call(this,a,b,"Leave a reply…",200,d);this.ma=a.get("route-builder");this.xf=a.get("notes-data");this.nb=c;this.Tea=g||null;this.Qe=e},d7a=function(a,b,c){var d=
'\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||a.t9;b=a.notes.length||a.hW;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.Xy({title:(0,z.N)(z.A(v6a())+" ("+z.A(a.quotes.length)+")"),Vf:!0},c)),k;k={gla:a.quotes,vLa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!k.vLa)var p=z.n("Learn more"),l=l+z.A(z.Xy({title:(0,z.N)(""+z.A(v6a())),Vf:!0,Qg:(0,z.N)(""+z.A(z.Wy({href:(0,z.M)(""+z.G((0,z.ji)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),
moreText:(0,z.N)(""+p),zb:!0},c)))},c));for(var p="list u-marginTop5 u-marginBottom15"+(k.gla.length?"":" u-hide"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.gla,r=p.length,u=0;u<r;u++){for(var w=p[u],C="",H=w.quotes,R=H.length,Q=0;Q<R;Q++)C+=""+H[Q].quoteId+(Q!=R-1?",":"");C=z.E(C);l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(C)+'" data-quote-creator-id\x3d"'+z.F(w.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+
z.A(z.al(z.D({user:w.user,Ge:!0},k),c))+"\x3c/li\x3e"}k=(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.t9?" is-withEditor":"")+'"\x3e'+z.A(z.Xy({title:(0,z.N)(""+z.A(z.Nk())),Vf:!0},c)),a.t9&&c.supportsEdit&&c.isAuthenticated?(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.WO(z.D({user:c.currentUser,isCollapsed:!0,uD:!0,type:"quoteResponses",rv:(0,z.N)(""+
z.A(z.Ofa()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):k="",g=g+k+c7a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.ZIa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):
k?z.n("Private notes are visible to you and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.nj(z.D({name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.N)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={TKa:g,title:(0,z.N)(""+z.A(e)),Vf:!0,Qg:(0,z.N)(b),l:"heading--privateNotes"};b=(0,z.y)(z.Uy(z.D({Ti:(0,z.N)(""+z.Vy(b,c)),NHa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.hW?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=W7({note:g[k],post:a.post,jM:a.jM},0,c);a.hW?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.gk({action:"show-note-editor",text:(0,z.N)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.bl({user:c.currentUser,tf:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.gk({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.N)(""+z.A(k))},0,c))+z.A(z.gk({action:"hide-note-editor",text:(0,z.N)(""+z.A(b7a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.pE&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.hk({Eb:!0,Uc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.A(z.Kda())),title:(0,z.N)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.hk({Eb:!0,Uc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.A(z.Lda())),title:(0,z.N)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},c7a=function(a,b,c){return(0,z.y)(z.A(z.AP({posts:a.responses,source:"quoteResponses",
nU:!0},0,c)))},W7=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.al({user:a.note.author},c)):z.A(z.WN({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.Ak({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.Fja?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.mh(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.Tt(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.wg(k,z.yg)?(0,z.y)(l,z.uca(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?e7a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=W7({note:k,post:a.post,Fja:a.note.author.userId==k.author.userId},0,c);e=d;a.jM?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.xQ({user:c.currentUser,tf:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.gk({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.A(p))},0,c))+z.A(z.gk({action:"hide-reply-editor",text:(0,z.N)(""+z.A(b7a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.jM?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.gk({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.N)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+e7a({note:a.note,isPrimary:!0,mja:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},e7a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.mja?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.mja?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.gk({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},f7a=function(a,b,c){b="";if(0==a.h9)a=1==a.pE?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.pE)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Xg(z.dj({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.h9)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Xg(z.dj({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.h9){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign up and create a profile");b+=z.A(z.gk({text:(0,z.N)(""+d),jc:!0,source:(0,z.N)(""+z.A(z.li({name:c.j.kd.Sna,susiEntry:c.j.Ha.$E}))),l:"u-textUnderline"},0,c))+" "+a}return(0,z.y)(b)},X7=function(a,b,c,d,e,g,k,l){z.T.call(this);this.qa=a;this.ya=a.get("butter-bar");this.ib=b;this.Qe=c;this.hk=e;this.xe=a.get("quotes-data");this.xf=a.get("notes-data");this.Bj=a.get("responses-data");this.nf=g;this.Z0=d;this.X1=(this.sI=k)?k.$i():null;this.Nf=this.Hc=null;this.jk={};this.Vca=!!z.Vp();
this.Wca=!!z.Xp();this.kB=this.Vca&&this.Wca&&z.TE(b);this.gr=null;this.AP=0;this.$fa=k6a(this.xe,this.Qe);this.Jw=l;this.Wa(this.Wq());this.Vda=z.Vp()?2:3},g7a=function(a){a.rb(".js-block").forEach(function(a){this.Ta(a,"mouseenter",this.pua,this);this.Ta(a,"mouseleave",this.u3,this)},a)},h7a=function(a){a.rb(".js-note").forEach(function(a){this.Ta(a,"mouseenter",this.nua,this);this.Ta(a,"mouseleave",this.u3,this)},a)},i7a=function(a,b){var c=a.query(".js-note-"+b);a.jk[b]||(a.jk[b]=new V7(a.qa,
c.querySelector(".js-replyEditor"),a.ib.Na(),b,a.Qe),z.Yw(a,a.jk[b],"saving",a.Nxa,a),z.Yw(a,a.jk[b],"save",a.Ixa,a),z.Yw(a,a.jk[b],"fail",a.Gwa,a));z.cd(c,"is-noteEditorVisible");a.jk[b].focus()},j7a=function(a,b){var c=a.jk[b];c&&(c.hb()&&c.hd(""),a=a.query(".js-note-"+b),z.jd(a,"is-noteEditorVisible"))},k7a=function(a,b,c){var d=S7(a.nf,a.Qe);if(d){var e=[];a.Jw&&(e=a.Jw.quotes.map(function(a){return a.$i()}));(0,z.Mb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),
d=z.Xa(d,b);if(this.Jw)var l=a.getAttribute("name").split(" "),d=d&&(0,z.Qc)(l,z.Xa.bind(null,e));z.od(a,"is-selected",c&&d)},a)}},Y7=function(a){return(a=z.ps(a,function(a){return z.bd(a,"js-note-item")}))&&a.getAttribute("data-note-id")},l7a=function(a,b,c,d){b=new z.GE(b,300);b.Wa(c);b.subscribe("dismiss",d,a);b.ua();return b},Z7=function(a){var b=a.hc(),c=a.Dd();a=a.Ce();1<b.length&&(a=b[0].Ia().length);var d=new z.as;d.uq(b[0].getName());d.Gg(c);z.K(d,"endIndex",a);d.hd(b[0].Ia().substring(c,
a));return d},$7=function(a,b){b%=a.Vda;0>b&&(b=a.Vda-1);a.AP=b;(b=a.query(".js-highlightTip"))&&z.P(b,f7a,{h9:a.AP,pE:a.$fa})},a8=function(a,b,c,d){z.T.call(this);this.Wa(this.Wq(d));this.Fb=a.get("dom-monitor");this.ib=b;this.ada=!b.Ya().Zr()||b.Mb();this.nb=b.Na();this.nf=c;this.xe=a.get("quotes-data");this.Bj=a.get("responses-data");this.xf=a.get("notes-data");this.qw=null;this.Nh={}},m7a=function(a,b){b.forEach(function(a){a&&b8(this,a)},a)},b8=function(a,b){if(!a.qw)if(S7(a.nf,b)){var c=n7a(a,
b),c=o7a(a,c),c=p7a(a,c),c=q7a(a,c);a.Nh[b]=c;r7a(a,b)}else delete a.Nh[b]},s7a=function(a,b){if(!a.qw){var c=a.Nh[b];if(c){var d=c.length,c=p7a(a,c),c=q7a(a,c);a.Nh[b]=c;d!=c.length?r7a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},t7a=function(a,b,c){return z.Ua(a.Nh[b]||[],function(a){return a.Xa==c})},n7a=function(a,b){var c=[];M7(a.xf,b).Tg(function(a){var e=a.RC(),g;e?(g=this.xf.yT(e),e=g.kb(),g=z.J(g,"endIndex")):(e=0,g=a.hb().length);c.push({anchor:b,
startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.ada)return c;(a.xe.du[b]||[]).forEach(function(a){var e=u7a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);A7(a.Bj,b).forEach(function(a){var e=y7(a);e&&(e=z7(e)&&z7(e).oo())&&(e=u7a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},o7a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});
b.forEach(function(a){var b=z.Ta(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.QH(c[b],a):c.push(a)},a);return c},q7a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Ta(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.QH(c[b],a):c.push(a)}},a);return c},r7a=function(a,b){a.rb(".js-paragraphControl-"+b).forEach(z.fg);a.Nh[b]=a.Nh[b].map(function(a){var b=v7a(this,a),b=z.Zv(w7a,b);b.style.top=a.offsetTop+"px";a.Xa=
b;this.oa().appendChild(a.Xa);z.cd(b,"is-visible");return a},a)},v7a=function(a,b){var c=b.notes,d=b.responses,e=u7(a.xe,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,u=!1,w=!1,C={},H={},R=z.Up().userId,Q=a.ib.Ya().Af().mb();c.forEach(function(a){var b=a.aK();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==R&&l++,a.author.social&&a.author.social.isFollowing&&(C[a.author.userId]=a.author),H[a.author.userId]=!0)}),H[b.userId]=!0,b.userId==R&&l++,b.userId==Q?p++:
r++,b.social&&b.social.isFollowing&&(C[b.userId]=b))});e.forEach(function(a){a=a.user;H[a.userId]=!0;a.userId==R&&(u=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});d.forEach(function(a){a=a.Af();H[a.userId]=!0;a.userId==R&&(w=!0);a.social&&a.social.isFollowing&&(C[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.nb,nC:b.anchor,XIa:k,PJa:g,Yy:w,Py:l,Bka:p,YIa:r,T1a:e.length,Xy:u,aja:Object.keys(H).length,OGa:z.qb(C),pE:c.length}},u7a=function(a){var b=a.Dd(),
c=a.Ce();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},p7a=function(a,b){var c=z.tw();return b.map(function(a){var b=this.nf.get(a.anchor),g=this.ib.Zi(b);if(!g)return a;var k;4==g.type&&(g.Ia()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.tKa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.XQ)k+=
z.XQ[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.ww(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},w7a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.nC)+' u-noUserSelect"\x3e',e=z.y,g;if(a.XIa||a.PJa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.nC)+'"\x3e';var k;k={};k=(0,z.y)(z.nj(z.D({name:"asteriskFilled",
size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Py?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.aja&&(0<a.Py||a.Xy||a.Yy)&&(0<a.Py&&a.Xy&&a.Yy?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Py&&a.Yy?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Py&&a.Xy?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.Xy&&a.Yy?(p=z.n("highlighted and responded"),l+=" "+p):a.Xy?
(p=z.n("highlighted"),l+=" "+p):0<a.Py?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.Yy&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.Bka&&0==a.YIa&&!a.Xy&&!a.Yy)c=1==a.Bka?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.pE)var u=z.n("Top highlight"),r=r+u;p+=z.A(z.kP(z.D({social:a.OGa,isActive:0<a.Py||a.Xy||a.Yy,Fi:a.aja,H6:!0,jJa:!0,zha:(0,z.N)(r)},a),c));p+=z.A(l)}p=(0,z.N)(p);k+=z.A(z.NIa(z.D({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},c8=function(a,b,c){z.T.call(this);this.qa=a;this.Ja=a.get("app");this.Vsa=a.get("floating-components");this.Oa=a.get("screen");this.tb=a.get("screen-service");this.Fb=a.get("dom-monitor");this.ib=b;this.Ud=b.Ud;this.pm=this.Ud.querySelector(".js-postField");this.mea=this.Oa.oa().querySelector(".js-notesPositionContainer");this.xe=a.get("quotes-data");this.xf=a.get("notes-data");this.xf.subscribe("new_note_list",this.dxa,this);
this.Bj=a.get("responses-data");this.nm=null;this.nf=new R6a(this.Ud.querySelector(".js-notesSource"));this.NH=this.Nh=this.kR=null;this.Nh=new a8(a,b,this.nf,this.mea);this.track(this.Nh);this.NH=this.Nh.oa();this.ih=this.D0=null;this.Se=c},e8=function(a,b){if(a.isActive()){var c=(b=b||a.D0)&&b.fU,d=b&&b.noteId;c&&(a.jx(c),d&&a.xf.Up(d,c)&&a.ih&&z.t(a.ih,function(){return d8(a,c,null,d)}));z.joa(a.Ja,"")}else a.D0=b||null},d8=function(a,b,c,d,e,g){var k={Ik:!0,A6:z.cw()};a.g2();c=new X7(a.qa,a.ib,
b,d||"",c||null,a.nf,e||null,g||null);c.subscribe("set-active-highlight",a.ifa,a);c.subscribe("reset-highlight",a.uAa,a);c.subscribe("close",a.g2,a);b=g&&g.Xa?g.Xa:a.nf.get(b);g=z.oya(a.Vsa);g.Sn=b;b=g.tE(c);b.kJ=k;k=b.SW(a.Mn.bind(a));k.eR=!0;a.nm=k.ua()},x7a=function(a,b,c){var d=a.ib.Zi(S7(a.nf,b));if(d&&4!=d.type){z.Zs(d,4);if(c){if(!P6a(c,d))return;z.Xs(d,z.Gs(c.startIndex,c.endIndex,c.id))}c=a.ib.Mb();var e=a.ib.Ya();c={mode:c?"edit":"view",Rj:z.lt(e),media:null,am:null,sections:!0,Jk:!1,Gk:!1,
El:!1,Pf:!1,postId:e.id};a.nf.get(b).innerHTML=z.It(d,z.im,c)}},y7a=function(a,b){var c=z.yn();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Tf();var d=T6a(a.nf,b);if(!d)return null;a=(b=z.ps(b,z.vB,d))&&a.ib.Zi(b);if(!b)return null;var d=z.yw(c,b,!0),e=z.yw(c,b,!1);return-1==d||-1==e?null:new Q6a(c,b,new z.as({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ia().substring(d,e)}))},z7a=function(){},f8=function(a,b){z.T.call(this);this.Rh=b||w6a;this.bb=a.get("screen-request");
this.va=null;this.E3=a.get("screen-view-state");this.qa=a;this.vfa=this.L2=!1;this.s1=this.Hc=null},g8=function(a){z.Ww.call(this);this.wz=a},A7a=function(a,b,c){a=z.ra(a)?new z.Xd(a):a;(a=E6a(a,b,c||{}))&&(new g8(a)).focus()},B7a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder")},h8=function(a){z.km.call(this);this.qa=a;this.sG=a.get("dialog");this.pa=a.get("request");this.ma=a.get("route-builder");this.ya=a.get("butter-bar");this.rJ=this.Fa=this.Bx=this.va=null;this.FP=!1},D7a=
function(a){var b=a.Fa.query(".js-tweetEditor-image"),c=a.Fa.query(".js-tweetEditor-imageContainer"),d=a.Fa.query(".js-tweetEditor-imageStatus");z.cd(c,"u-hide");var e=C7a(a);e.base64=!0;z.v(z.t(a.pa.post(z.Yv(H6a),e,{oC:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.jd(c,"u-hide");z.cd(d,"u-hide");this.FP=!0},a),function(a){z.Sw(a);z.P(d,J6a)},a)},E7a=function(a,b){return 280>=C7(b)?!0:(b=a.Fa.query(".js-tweetEditor-text"),(new z.Az(b,{name:"shimmy-shake",duration:400})).start(),
a=a.Fa.query(".js-tweetEditor-error"),z.P(a,N6a),!1)},C7a=function(a){var b=a.va,c=a.Bx.QKa;a=a.Bx.PKa;var d=b.creator,e=b.approvedHomeCollection,g=z.im,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.lKa(e.tintColor),r=z.Nr(r,.6).color);return new E7({content:c,altText:a,title:b.title,author:d&&d.name,date:z.lh(b.createdAt,g),authorAvatarId:d&&d.imageId,
collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,collectionHighlightColor:r,version:2})},F7a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder");this.qa=a};z.q(s7,z.L);z.f=s7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return"Placement"};z.f.uf=function(){return z.J(this,"items")};z.f.Kc=z.h(392);z.f.aM=function(a){return z.K(this,"location",a)};z.f.Cd=z.h(435);z.f.Yb=function(a){return z.K(this,"index",a)};
z.f.ha=function(){return s7.prototype};z.f.fa={name:"Placement",ia:!1,fields:{items:{name:"items",g:function(){return z.cM},ra:z.V,h:1},location:{name:"location",g:function(){return z.FBa},h:2},index:{name:"index",g:z.X,h:3}},ka:{}};z.f.Cd=z.Y(435,function(){return z.J(this,"index")});z.f.Kc=z.Y(392,function(a){return z.K(this,"items",a)});z.m(v7,z.Ge);v7.prototype.Ak=function(a){var b={};z.pD(this,b,a.Ob(),"");return b};
v7.prototype.Jb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.Fh(g,k);if(!l)break;var p=l.g();if(l.ra()){var r=z.Ah(g,k)||[],u=e.shift(),w=Number(u);if(void 0===u||!Number.isInteger(w)||0>w)break;if(p.prototype instanceof z.sh)l=r[w],l||(l=new p,r[w]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=d6a(b[a],l);r[w]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.sh)r=z.Ah(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=d6a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(w7,z.Hh);z.f=w7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.RT=z.h(578);z.f.ha=function(){return w7.prototype};z.f.fa={name:"PlacementsResponse",ia:!1,fields:{placements:{name:"placements",g:function(){return s7},ra:z.V,h:1}},ka:{}};z.q(x7,z.L);x7.prototype.ca=function(){return""};x7.prototype.ea=function(){return""};x7.prototype.ha=function(){return x7.prototype};
x7.prototype.fa={name:"PlacementsRequestQuery",ia:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.kq},h:1},slots:{name:"slots",g:function(){return z.Rq},ra:z.V,h:2}},ka:{}};z.VW.prototype.bW=z.Y(593,function(a){a!=this.VP&&this.Ab&&(this.Ab.ii.contentEditable=a);this.VP=a});z.aG.prototype.SW=z.Y(584,function(a){this.Mn=a;return this});z.fG.prototype.SW=z.Y(583,function(a){this.Mn=a;return this});
z.MF.prototype.C5=z.Y(582,function(a){a=y7(a);if(!a)return null;a=z7(a)&&z7(a).oo();return a?(a=a.hc())&&a.length?a[0].getName():null:null});w7.prototype.RT=z.Y(578,function(){return z.J(this,"placements")});z.qD.prototype.RT=z.Y(577,function(a,b){var c=this;a=f6a(g6a(new x7,a),b);a=(new v7).Ak(a);var d=this.ma.la(z.Jza,{},a);return z.rD(this,d,function(){return z.t(c.pa.get(d,{background:!0}),function(a){a=c.Ka.lc(w7,a);c.Aa.qc(a);return a})})});
z.px.prototype.Up=z.Y(494,function(){return z.J(this,"note")});z.kD.prototype.Up=z.Y(493,function(a){return this.mc("Note",a)});z.$r.prototype.my=z.Y(463,function(){return z.J(this,"replyId")});z.px.prototype.my=z.Y(462,function(){return z.J(this,"replyId")});z.Yr.prototype.ez=z.Y(461,function(a){return z.K(this,"highlight",a)});z.Yr.prototype.yT=z.Y(460,function(){return z.J(this,"highlight")});z.Yr.prototype.wv=z.Y(459,function(a){return z.K(this,"author",a)});
z.$r.prototype.wv=z.Y(458,function(a){return z.K(this,"author",a)});z.Yr.prototype.aK=z.Y(457,function(){return z.J(this,"author")});z.$r.prototype.aK=z.Y(456,function(){return z.J(this,"author")});z.Yr.prototype.RC=z.Y(455,function(){return z.J(this,"highlightId")});z.Yr.prototype.Ts=z.Y(454,function(a){return z.K(this,"state",a)});z.$r.prototype.Ts=z.Y(453,function(a){return z.K(this,"state",a)});z.jx.prototype.Ts=z.Y(452,function(a){return z.K(this,"state",a)});
z.Yr.prototype.yg=z.Y(451,function(){return z.J(this,"noteId")});z.$r.prototype.yg=z.Y(450,function(){return z.J(this,"noteId")});z.px.prototype.yg=z.Y(449,function(){return z.J(this,"noteId")});z.sr.prototype.xv=z.Y(448,function(a){return z.K(this,"authorId",a)});z.Yr.prototype.xv=z.Y(447,function(a){return z.K(this,"authorId",a)});z.$r.prototype.xv=z.Y(446,function(a){return z.K(this,"authorId",a)});z.Jp.prototype.Le=z.Y(343,function(){return z.J(this,"catalogId")});
z.oK.prototype.Le=z.Y(342,function(){return z.J(this,"catalogId")});z.fK.prototype.Le=z.Y(341,function(){return z.J(this,"catalogId")});z.dK.prototype.Le=z.Y(340,function(){return z.J(this,"catalogId")});z.cM.prototype.Le=z.Y(339,function(){return z.J(this,"catalogId")});z.KJ.prototype.Le=z.Y(338,function(){return z.J(this,"catalogId")});z.IL.prototype.Le=z.Y(337,function(){return z.J(this,"catalogId")});z.DK.prototype.Le=z.Y(336,function(){return z.J(this,"catalogId")});
z.AL.prototype.Le=z.Y(335,function(){return z.J(this,"catalogId")});z.zL.prototype.Le=z.Y(334,function(){return z.J(this,"catalogId")});z.yL.prototype.Le=z.Y(333,function(){return z.J(this,"catalogId")});z.sr.prototype.Le=z.Y(332,function(){return z.J(this,"catalogId")});z.px.prototype.Le=z.Y(331,function(){return z.J(this,"catalogId")});z.wH.prototype.Le=z.Y(330,function(){return z.J(this,"catalogId")});z.Do.prototype.UT=z.Y(83,function(){return z.J(this,"point")});var q6a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;
B7.prototype.UT=function(){var a=window.document.body;return z.mg(a,this.oi.node)?this.oi:this.Tk&&z.mg(a,this.Tk)?z.PM(this.tQ,this.Tk):this.Qe&&(a=z.ss(this.Rsa,this.Qe))?z.PM(this.tQ,a):null};z.q(D7,z.Km);D7.prototype.yL=function(){if(!this.pk)return null;var a=this.pk.UT();if(!a)return null;var b=this.um.UT();return b?z.ln(a.node,a.offset,b.node,b.offset):null};z.q(E7,z.L);z.f=E7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.hb=function(){return z.J(this,"content")};
z.f.hd=function(a){return z.K(this,"content",a)};z.f.Ib=function(){return z.J(this,"title")};z.f.Qc=function(a){return z.K(this,"title",a)};z.f.aK=function(){return z.J(this,"author")};z.f.wv=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Hb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.fM=function(a){return z.K(this,"template",a)};
z.f.Zd=function(){return z.J(this,"subtitle")};z.f.Ef=function(a){return z.K(this,"subtitle",a)};z.f.ha=function(){return E7.prototype};
z.f.fa={name:"TextshotInfo",ia:!1,fields:{content:{name:"content",g:z.W,h:1},altText:{name:"altText",g:z.W,h:2},title:{name:"title",g:z.W,h:3},author:{name:"author",g:z.W,h:4},date:{name:"date",g:z.W,h:5},authorAvatarId:{name:"authorAvatarId",g:z.W,h:6},collection:{name:"collection",g:z.W,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.W,h:8},collectionLogoId:{name:"collectionLogoId",g:z.W,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.W,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.W,h:11},version:{name:"version",g:z.X,h:12},base64:{name:"base64",g:z.FH,h:13},template:{name:"template",g:z.W,h:14},mainStat:{name:"mainStat",g:z.W,h:15},mainStatTitle:{name:"mainStatTitle",g:z.W,h:16},subtitle:{name:"subtitle",g:z.W,h:17},icon:{name:"icon",g:z.W,h:18},imgKey:{name:"imgKey",g:z.W,h:19}},ka:{}};var G7a={eTa:"quote-respond"};z.q(G7,z.T);z.f=G7.prototype;z.f.Bk=function(){return this.Am.Bk()};
z.f.na=function(){G7.xa.na.call(this);z.Yw(this,this.x_,"data-redirect-type-quote",this.nwa,this);this.Ta(this.Ud,"click",this.Cw,this);z.UE(this.ib)&&z.aw()&&this.Ta(this.Ud,"mouseover",this.Hta,this);this.ib.Ya().Zr()&&!this.ib.Mb()&&z.v(this.xe.load(this.ib.Na()),z.Sw);var a=this.Bk();a&&(z.Yw(this,a,"quote",this.Eta,this),z.Yw(this,a,"quote-respond",this.Fta,this),z.Yw(this,a,"show",this.w3,this),z.Yw(this,a,"hide",this.Hwa,this))};
z.f.nwa=function(a){var b=z.CE(this.Am,this.Bk().xx);b&&(a.url=new z.Xd(this.ma.la(z.QCa,{postId:this.ib.Na()},{paragraphs:JSON.stringify([b.ty.Jb().Ob()]),startOffset:b.start,endOffset:b.end})))};z.f.Cw=function(a){z.ps(a.target,function(a){if(a===this.Ud)return!0;var c=z.EB(a);if(3==c)return!0;if(7==c){if(c=A6a(this,a))if(H7(this,c),z.aw())J7(this,c);else{var d=new z.EE;y6a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.Hta=function(a){z.ps(a.target,function(a){if(a===this.Ud)return!0;var c=z.EB(a);if(3==c)return!0;if(7==c){c=z.yn();if(!(c&&!c.isCollapsed()||this.Bk()&&this.Bk().Zm())&&(c=A6a(this,a))){var d=this.Ud.querySelector('.markup--quote[name~\x3d"'+c.$i()+'"]');a=new z.GE(a,100);y6a(this,c,d,a);H7(this,c)}return!0}return!1}.bind(this))};
z.f.w3=function(){var a=z.yn();a&&!a.isCollapsed()&&H7(this,null);if(z.UE(this.ib)&&(a=z.CE(this.Am,this.Bk().xx))){var a=z.Gva(this.xe,a.ty,a.start,a.end),b=this.Bk().Sa().querySelector(".js-highlightMenuQuoteButton");z.od(b,"is-active",!!a)}};z.f.Hwa=function(){this.Gp&&H7(this,null)};
z.f.Eta=function(){if(z.UE(this.ib)){var a=z.xE(this.Bk());if(a){var b=a.range,c=a.hIa,a=this.Bk().Sa().querySelector(".js-highlightMenuQuoteButton"),d=z.bd(a,"is-active"),b=z.CE(this.Am,b);z.v(z.t(this.xe.toggle(b.ty,b.start,b.end,!c),function(a){z.pKa();d?z.zE(this.Bk()):J7(this,a);var b=c?"selection_menu":"quote_click_menu";K7(this,a.$i(),!d,b)},this),z.Sw)}}};
z.f.Fta=function(){if(z.UE(this.ib)&&z.im.supportsEdit){var a=z.xE(this.Bk());if(a){var b=z.CE(this.Am,a.range);z.v(z.t(this.xe.create(b.ty,b.start,b.end,1,!0),function(a){K7(this,a.$i(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.ty.name)},this),z.Sw)}}};
z.f.Ota=function(a){var b=this.Gp,c=I7(this,b),d=b.Dd(),e=b.Ce(),b=a.query(".js-quoteAttributions-pileOn"),g=z.bd(b,"is-active");z.v(z.t(this.xe.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.pd(l,"is-active");if(l=z.tE(this.xe,c,d,e)){var p=x6a(this,l),r=a.query(".js-quoteAttributions-info");z.P(r,p6a,p)}else a.Lc();!g&&z.aw()&&(a.Lc(),J7(this,l));l=z.aw()?"quote_hover":"quote_click_mobile";K7(this,b.$i(),!g,l)},this),z.Sw)};
z.f.Pta=function(){if(z.UE(this.ib)&&z.im.supportsEdit){var a=I7(this,this.Gp),b=this.Gp.Dd(),c=this.Gp.Ce();z.v(z.t(this.xe.create(a,b,c,1,!0),function(b){K7(this,b.$i(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.Sw)}};z.f.Qta=function(){var a=C6a(this,this.Gp);a&&z.Qva(this.Am,a)};
z.f.Xea=function(){var a=new D7(this.Ud),b=this.xe.du,c=Object.keys(b).concat(this.wba);z.gb(c);c.forEach(function(a){var c=b[a]||[],g=this.ib;if(g=(a=g.Ud&&z.ss(g.Ud,a))&&this.ib.Zi(a))o6a(g,c),a.innerHTML=z.It(g,z.im,z.fwa(this.ib)),z.Bya(this.wza,a)},this);this.wba=Object.keys(b);(a=a.restore())&&a.select()};z.q(L7,z.Ww);z.f=L7.prototype;
z.f.load=function(a){if(!z.Vp())return z.Sc([]);this.nb=a;this.Jh||(this.Jh=z.v(z.t(this.rl.get(this.ma.la(z.ICa,{postId:a}),{background:!0}),this.uza,this),z.Sw));return this.Jh.Zc()};z.f.eq=function(){return this.tba};z.f.Mj=function(){return this.uea};z.f.yT=function(a){return this.Jca[a]||null};z.f.Up=function(a,b){return z.xN(M7(this,b),a)};z.f.ez=function(a,b){this.Jca[a]=b};z.f.Na=function(){return this.nb};
z.f.uza=function(a){var b=a.references.User;this.uea=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=M7(this,g);e=z.Zr(e);g.add(z.pC(this.Aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.ez(a[b].id,z.vo.Jb(z.as,a[b]));this.tba=!0};z.m(P7,z.T);P7.prototype.na=function(){var a=this;z.T.prototype.na.call(this);z.t(this.bb.RT(this.mAa,this.hza),function(b){b.placements&&b.placements.forEach(a.Cua,a)})};P7.prototype.Cua=function(a){if(this.isActive()){var b;switch(a.location){case 1:b=this.Oa.query(".js-postFooterPlacements");if(!b)break;z.P(b,z.wP,{items:a.items,context:9});z.U(b).ba("show-more-recommendations",this.TBa,this);break;case 2:(b=this.Oa.query(".js-readNextMetabarRight"))&&z.P(b,z.wP,{items:a.items,context:2})}}};
P7.prototype.TBa=function(a){z.ux(z.wGa,{});var b=this.Oa.query(".js-moreRecommendations");b&&(z.vs(b),z.us(a.target))};z.m(Q7,z.T);z.f=Q7.prototype;
z.f.na=function(){var a=this;z.T.prototype.na.call(this);this.sp&&(z.Yw(this,this.sp,z.eHa,function(){z.cd(a.oa(),"is-abovePostActions");a.TP=!0}),z.Yw(this,this.sp,z.fHa,function(){z.jd(a.oa(),"is-abovePostActions");a.TP=!1}));z.U(this.oa()).ba("dismiss-meter",this.vt,this).ba("expand-meter",this.Lsa,this);var b=this.nh.postIds&&1<this.nh.postIds.length,c=z.Lp().isMobile&&!z.Lp().isTablet;if(b||c)this.gw=(0,window.setTimeout)(this.vt.bind(this),H7a);z.t(z.Gm(300),this.Vza,this)};
z.f.Ca=function(){this.ih&&(this.ih.cancel(),this.ih=null);this.gw&&((0,window.clearTimeout)(this.gw),this.gw=null);z.T.prototype.Ca.call(this)};z.f.vt=function(){var a=this;this.ih=new z.Az(this.oa(),{name:this.TP?z.Lp().isMobile?"pop-shift-down-35":"pop-shift-down-44":"pop-shift-down-0",duration:550,timing:"ease-in-out"});z.t(this.ih,function(){z.us(a.oa());z.vs(a.Oa.query(".js-openInAppButton"))});this.ih.start()};
z.f.Lsa=function(a){a=a.target;var b=this.query(I7a),c=this.query(J7a);z.us(a);z.cd(b,"is-visible");this.gw&&((0,window.clearTimeout)(this.gw),this.gw=null);z.P(c,z.Zwa);z.jd(c,"u-xs-hide");z.ux(z.EGa,{unlockCount:this.nh.postIds.length})};
z.f.Vza=function(){var a=this;this.Oa.oa().appendChild(this.oa());z.t((new z.Az(this.oa(),{name:this.TP?z.Lp().isMobile?"pop-shift-up-35":"pop-shift-up-44":"pop-shift-up-0",duration:800,timing:"ease-in-out"})).start(),function(){if(a.nh&&a.nh.postIds&&a.nh.postIds.length){for(var b=a.rb(".js-meterThumbnail"),c=new z.Ec,d=0;d<a.nh.postIds.length;d++)z.t(c,a.uY.bind(a,b[d],d==b.length-1));c.callback()}})};
z.f.uY=function(a,b){b=new z.Az(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.t(new z.Az(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.cd(a,"is-read")}),d=new z.Az(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.jm([b.start(),c.start(),d.start()])};var H7a=6E3,J7a=".js-dismissMeterIndicator",I7a=".js-moreInfo";R7.prototype.XS=function(a,b,c){return new G7(a,b,c)};R7.prototype.gs=function(){return G7a};R6a.prototype.get=function(a){return S7(this,a)};z.q(T7,z.VW);z.f=T7.prototype;z.f.QI=!1;z.f.fB="";z.f.RI=0;z.f.xs=z.V;z.f.yg=function(){return this.Z0};z.f.save=function(){this.hb().length<=this.zm&&this.ul()};z.f.Gb=function(){(0,window.clearTimeout)(this.RI);T7.xa.Gb.call(this)};
z.f.na=function(){function a(a){a.stopPropagation()}T7.xa.na.call(this);this.fB=this.hb();this.hd(this.fB);this.Lx(13,this.c1,this);this.Lx(27,this.d1,this);this.Ab.Ta("blur",this.b1,!1,this);var b=this.Ab.Sa();z.lw(b,"keydown",a);z.lw(b,"keyup",a);z.lw(b,"keypress",a)};z.f.M7=function(a){return a};
z.f.ul=function(){if(this.isEnabled()){var a=this.hb().trim();if(a){this.bW(!1);var b=this.oia(),a=this.nia(a);this.za("saving",a);z.Mc(z.v(z.t(this.rl.post(b,a.Ob()),this.hxa,this),this.fxa.bind(this,a)),this.bW.bind(this,!0))}}};z.f.hxa=function(a){this.za("save",this.M7(a.value))};z.f.fxa=function(a,b){this.za("fail",a);this.Fa.error(U6a());z.Sw(b)};z.f.c1=function(a){if(this.Ir&&z.EX(this.Ir))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.d1=function(a){if(this.Ir&&z.EX(this.Ir))return!1;a.preventDefault();this.hd(this.fB);this.za("cancel");return!1};z.f.b1=function(){this.QI&&(this.hb().length>=this.zm?(0,window.confirm)(this.ria())?(this.hd(this.fB),this.za("cancel")):this.focus():this.RI=(0,window.setTimeout)(this.ul.bind(this),100))};z.q(U7,T7);z.f=U7.prototype;z.f.rY=null;z.f.Naa=null;z.f.sY=null;z.f.hk=null;z.f.S_=null;z.f.R_=null;z.f.Ica=null;z.f.ez=function(a){this.hk=a;this.S_=a.startIndex;this.R_=a.endIndex;this.Ica=a.content;return this};z.f.ria=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.M7=function(a){var b=z.Wv();a=z.Zr(a).wv(b).xv(b.mb());this.hk&&a.RC()&&this.xf.ez(a.RC(),this.hk);var b=this.xf,c;c=z.pC(b.Aa,a);M7(b,c.ge()).add(c);return a};
z.f.oia=function(){return this.yg()?this.ma.la(z.JCa,{postId:this.nb,noteId:this.yg()}):this.ma.la(z.HCa,{postId:this.nb})};z.f.nia=function(a){var b=z.Wv();a=(new z.Yr({content:a,anchor:this.rY,anchorContent:this.Naa,anchorImage:this.sY?this.sY.Ob():null,replies:[],createdAt:Date.now()})).wv(b);null!=this.S_&&null!=this.R_&&(b=new z.as({anchor:this.rY,startIndex:this.S_,endIndex:this.R_,content:this.Ica}),a.ez(b));return a};z.q(V7,T7);V7.prototype.ria=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};V7.prototype.M7=function(a){var b=z.Wv();a=z.Aja(a).wv(b).xv(b.mb());z.J(this.xf.Up(a.yg(),this.Qe),"replies").push(a);return a};V7.prototype.oia=function(){return this.Tea?this.ma.la(z.MCa,{postId:this.nb,noteId:this.yg(),replyId:this.Tea}):this.ma.la(z.LCa,{postId:this.nb,noteId:this.yg()})};
V7.prototype.nia=function(a){var b=z.Wv();return(new z.$r({replyId:"",postId:this.nb,noteId:this.yg(),content:a,createdAt:Date.now()})).wv(b)};z.q(X7,z.T);z.f=X7.prototype;
z.f.na=function(){X7.xa.na.call(this);z.U(this.oa()).ba("show-note-editor",this.Q2,this).ba("hide-note-editor",this.O_.bind(this,!0)).ba("show-reply-editor",this.gCa,this).ba("hide-reply-editor",this.lua,this).ba("save-note",this.MAa,this).ba("save-reply",this.NAa,this).ba("highlight-quote",this.oua,this).ba("dismiss-note",this.Aba.bind(this,!0),this).ba("delete-note",this.Aba.bind(this,!1),this).ba("delete-reply",this.$ra,this).ba("previous-highlight-tip",this.sza,this).ba("next-highlight-tip",this.Qva,
this);h7a(this);this.Bj&&t7(this.Bj)&&(g7a(this),z.Yw(this,t7(this.Bj),"add",this.exa,this));if(this.X1&&this.Vca&&this.Wca){var a=this.query(".js-inlineNewPostControl"),b=this.X1,c=this.ib.Na(),d=new z.PS(this.qa);d.WL("web-inline-quote-responses");d.Wa(a);d.uG=!0;d.yZ=!0;d.vZ=!0;d.fM(r6a);d.eB=b;d.$L(c);z.QS(d,!0);this.Hc=d;this.Hc.ua();a=Z7(this.sI);this.za("set-active-highlight",this.Qe,a)}this.hk&&(this.Q2(),this.Nf&&this.Nf.focus());$7(this,0)};
z.f.Ca=function(){this.gr&&this.gr.O4();(this.hk||this.sI)&&this.za("reset-highlight",this.Qe,null);X7.xa.Ca.call(this)};z.f.Gb=function(){z.Bx(this.oa());z.fg(this.oa());z.mm(this.Hc);z.mm(this.Nf);z.mm(this.gr);z.nm(z.qb(this.jk));this.gr=this.jk=this.Nf=this.Hc=null;X7.xa.Gb.call(this)};z.f.wo=function(){if(this.Nf&&this.Nf.hb())return!0;for(var a=z.qb(this.jk),b=0;b<a.length;b++)if(a[b]&&a[b].hb())return!0;return this.Hc&&!this.Hc.isDismissable()?!0:!1};
z.f.Wq=function(){var a=[],b=[],c=[],d=this.kB&&(this.hk||this.sI);d||(this.Jw?(a=this.xe?u7(this.xe,this.Jw.quotes):[],b=this.Jw.notes,c=this.Jw.responses):(b=this.xf?z.UC(M7(this.xf,this.Qe)):[],this.Z0||(this.xe?(a=this.xe,a=u7(a,a.du[this.Qe]||[])):a=[],c=this.Bj?A7(this.Bj,this.Qe):[])));return z.Zv(d7a,{post:this.ib.Ya(),quotes:a,notes:b,responses:c,t9:!!this.X1,hW:d,jM:this.kB,pE:this.$fa,ZIa:z.TE(this.ib)})};
z.f.exa=function(){var a=this.query(".js-postList"),b=z.Zv(c7a,{responses:A7(this.Bj,this.Qe)});z.gg(b,a);g7a(this)};
z.f.Q2=function(){if(this.kB){if(!this.Nf){var a=this.query(".js-noteEditor"),b=z.Yv(a7a),a=this.Nf=new U7(this.qa,a,this.ib.Na(),null,b),b=this.Qe,c=this.ib.Zi(this.nf.get(this.Qe)),d=c.Ia(),c=4==c.type?c.De():null;a.rY=b;a.Naa=d;a.sY=c;(a=this.hk)&&this.Nf.ez(a);z.Yw(this,this.Nf,"saving",this.Mxa,this);z.Yw(this,this.Nf,"fail",this.Fwa,this);z.Yw(this,this.Nf,"save",this.Hxa,this)}z.cd(this.query(".js-noteActions"),"is-noteEditorVisible");this.Nf&&this.Nf.focus()}};
z.f.MAa=function(){this.Nf&&this.Nf.save()};z.f.Mxa=function(a){this.Nf.hd("");var b=this.query(".js-notesList");a={note:a,post:this.ib.Ya(),hW:this.kB,jM:this.kB};a=z.Zv(W7,a);b.appendChild(a);z.jd(b,"is-empty");h7a(this);this.O_()};z.f.Hxa=function(a){var b=this.query(".js-notesList").lastChild;a=a.yg();z.cd(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Fwa=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.cd(a,"is-empty");this.Q2()};z.f.O_=function(a){a?this.za("close"):this.Nf&&(this.Nf.hb()&&this.Nf.hd(""),z.jd(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.gCa=function(a){(a=Y7(a.target))&&this.kB&&i7a(this,a)};z.f.NAa=function(a){a=Y7(a.target);(a=this.jk[a])&&a.save()};
z.f.Nxa=function(a){var b=a.yg();this.jk[b]&&this.jk[b].hd("");var c=this.xf.Up(b,this.Qe).author.userId==a.author.userId,d=this.query(".js-note-"+a.yg()+" .js-repliesList");a={note:a,post:this.ib.Ya(),Fja:c};a=z.Zv(W7,a);d.appendChild(a);z.jd(d,"is-empty");j7a(this,b)};z.f.Ixa=function(a){var b=this.query(".js-note-"+a.yg()).querySelector(".js-repliesList").lastChild;a=a.my();z.cd(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Gwa=function(a){var b=this.query(".js-note-"+a.yg()+" .js-repliesList");b.removeChild(b.lastChild);z.cd(b,"is-empty");i7a(this,a.yg())};z.f.lua=function(a){(a=Y7(a.target))&&j7a(this,a)};z.f.oua=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=S7(this.nf,this.Qe);c&&(this.gr&&this.gr.O4(),this.gr=l7a(this,c,a,function(){k7a(this,b,!1);z.mm(this.gr);this.gr=null}),k7a(this,b,!0))};
z.f.nua=function(a){var b=S7(this.nf,this.Qe);(a=this.xf.Up(a.target.getAttribute("data-note-id"),this.Qe))&&b&&(b=(b=a.RC())?this.xf.yT(b):null,this.za("set-active-highlight",this.Qe,b))};z.f.pua=function(a){var b=S7(this.nf,this.Qe),c;c=this.Bj;a=a.target.getAttribute("data-post-id");c=t7(c)?z.xN(t7(c),a):null;b&&c&&(b=y7(c))&&(b=z7(b)&&z7(b).oo())&&(c=b.hc())&&c.length&&(b=Z7(b),this.za("set-active-highlight",this.Qe,b))};
z.f.u3=function(){var a=null;this.sI&&(a=Z7(this.sI));this.hk&&(a=this.hk);this.za("reset-highlight",this.Qe,a)};
z.f.Aba=function(a,b){b=b.value;var c=this.xf.Up(b,this.Qe),d=this.query(".js-note-"+b);if(c&&d){z.us(d);this.u3();this.rb(".js-note-item").every(function(a){return z.bd(a,"u-hide")})&&this.O_(!0);var e=N7(this.xf,c,"HIDDEN");z.v(e.Il,function(b){this.ya.ua(a?V6a():W6a(),"error");e.DL();z.vs(d);(400>b.status||499<b.status)&&N7(this.xf,c,"NEW")},this);z.t(this.ya.ua(a?Y6a():Z6a(),{type:"success",qE:!0}),function(){this.ya.Lc();e.DL();N7(this.xf,c,"NEW");z.vs(d)},this)}};
z.f.$ra=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=Y7(a.target);if(d&&c){z.us(c);var e=O7(this.xf,b,d,this.ib.Na(),this.Qe,"HIDDEN");z.v(e.Il,function(){this.ya.ua(X6a(),"error");e.DL();z.vs(c);O7(this.xf,b,d,this.ib.Na(),this.Qe,"")},this);z.t(this.ya.ua($6a(),{type:"success",qE:!0}),function(){this.ya.Lc();e.DL();O7(this.xf,b,d,this.ib.Na(),this.Qe,"");z.vs(c)},this)}};z.f.sza=function(){$7(this,this.AP-1)};z.f.Qva=function(){$7(this,this.AP+1)};z.q(a8,z.T);z.f=a8.prototype;z.f.na=function(){a8.xa.na.call(this);var a=[];z.TE(this.ib)&&a.push(this.xf.load(this.nb));this.ada||(a.push(this.xe.load(this.nb)),a.push(this.Bj.load(this.nb)));this.qw=z.t(z.t(z.t(z.ER(a),function(){this.qw=null},this),this.render,this),this.Wqa,this);z.Yw(this,this.Fb,"resize-end",this.Xf,this)};z.f.Ca=function(){this.qw&&this.qw.cancel();a8.xa.Ca.call(this)};z.f.Gb=function(){this.qw=null;a8.xa.Gb.call(this)};
z.f.render=function(){S6a(this.nf,function(a,b){b8(this,b)},this)};z.f.Xf=function(){S6a(this.nf,function(a,b){s7a(this,b)},this)};z.f.Wqa=function(){var a=this.xe.tp;z.Yw(this,a,"add",this.cea,this);z.Yw(this,a,"remove",this.cea,this);(a=t7(this.Bj))&&z.Yw(this,a,"add",this.Exa,this)};z.f.cea=function(a){m7a(this,Object.keys(z.Kva(this.xe,a instanceof Array?a:[a])))};z.f.Exa=function(a){m7a(this,(a instanceof Array?a:[a]).map(this.Bj.C5,this.Bj))};
z.f.Wq=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};z.f.QH=function(a,b){z.Gb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(c8,z.T);z.f=c8.prototype;
z.f.na=function(){c8.xa.na.call(this);this.Ta(this.Oa.oa(),"click",this.rva,this,!0);z.U(this.NH).ba("select-anchor",this.Txa,this);var a=this.ib.Ya();if(a.Zr()&&!this.ib.Mb()){var b=z.Cp(a),b=2==a.visibility&&b&&!z.J(b.Qj(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.Bj.load(this.ib.Na(),"best"),z.Sw);z.v(this.xe.load(this.ib.Na()),z.Sw)}a.Qj().$J()&&(this.rQ=z.t(this.xf.load(this.ib.Na()),this.ixa,this));this.D0&&e8(this,null);z.Yw(this,this.tb,"historyUpdate",function(){e8(this,
z.IE())},this);this.Se&&z.Yw(this,this.Se,"highlight",this.gxa,this)};z.f.Gb=function(){z.mm(this.Nh);this.Nh=null;z.mm(this.nm);this.nm=null;this.NH&&z.U(this.NH).clear("select-anchor");this.rQ&&this.rQ.cancel();this.rQ=null;c8.xa.Gb.call(this)};z.f.fJa=function(a,b){d8(this,b,null,null,a)};z.f.fLa=function(){this.Nh&&this.Nh.Xf()};z.f.wo=function(){if(!this.nm)return!1;var a=this.nm.hb();return a?a.wo():!1};z.f.dxa=function(a){a.subscribe("add",this.iga,this);a.subscribe("remove",this.iga,this)};
z.f.iga=function(a){(z.pa(a)?a:[a]).forEach(function(a){b8(this.Nh,a.ge())},this)};z.f.ixa=function(){var a=(0,z.La)();this.rQ=null;e8(this,z.IE());this.Ta(this.pm,z.mI,this.n1,this);z.ly(z.aFa,(0,z.La)()-a)};z.f.n1=function(a){(a=a.target.getAttribute("name"))&&S7(this.nf,a)&&s7a(this.Nh,a)};z.f.gxa=function(){if(this.Se){var a=y7a(this,this.Se.xx);z.zE(this.Se);a&&(a=a.highlight,this.ifa(a.anchor,a),d8(this,a.anchor,a))}};
z.f.rva=function(a){if(this.nm){var b=a.target;if(!z.mg(this.nm.oa(),b)){var c=this.nm.hb(),d;if(!(d=!c)){a:if(c.Nf&&c.Nf.hb())c=!0;else{d=z.qb(c.jk);for(var e=0;e<d.length;e++)if(d[e]&&d[e].hb()){c=!0;break a}c=c.Hc&&!c.Hc.bj()?!0:!1}d=!c}d&&(c=this.nm&&this.nm.Sn,d="select-anchor"==b.getAttribute("data-action"),this.g2(),c&&d&&z.mg(c,b)&&a.stopPropagation())}}};
z.f.Mn=function(a){if(!z.cw()){var b=a.Sn,c=z.ww(b);a.Nl();a=a.oa();var d=z.ww(a),e=window.innerHeight,g=window.innerWidth,k=this.Oa.query(".js-metabar"),l=0;k&&(l=z.ww(k).height);d.height>=e-l?F6a(a):(z.sw(b),b=c.top+d.height>=e?z.tw().top+e-d.height-10:z.sw(b),c=z.ww(this.NH).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.g2=function(){z.mm(this.nm);this.nm=null};
z.f.Txa=function(a){var b=z.ps(a.target,function(a){return z.bd(a,"js-paragraphControl")},this.mea),b=t7a(this.Nh,a.value,b);d8(this,a.value,null,null,null,b)};z.f.ifa=function(a,b){if(this.ib.Mb()){var c=z.yn();this.kR=(c=c&&T6a(this.nf,c.Tf()))&&new D7(c)}x7a(this,a,b)};z.f.uAa=function(a,b){x7a(this,a,b);this.ib.Mb()&&this.kR&&(a=this.kR.restore())&&a.select();this.kR=null};
z.f.jx=function(a){if(this.nf&&(a=S7(this.nf,a))){a=Math.max(z.sw(a),0);var b=window.document.body;this.ih&&this.ih.cancel();this.ih=new z.to(b,"scrollTop",600,a)}};z7a.prototype.XS=function(a,b,c){return new c8(a,b,c)};z.m(f8,z.T);z.f=f8.prototype;z.f.pc=function(a){this.va=a};z.f.fM=function(a){this.Rh=a};z.f.kKa=function(a){this.L2=a};z.f.lKa=function(a){this.vfa=a};
z.f.na=function(){this.oa()?(z.T.prototype.na.call(this),z.U(this.oa()).ba("show-responses-stream-editor",this.eya,this).ba("show-other-responses",this.Bfa,this),z.P(this.oa(),this.Rh,{post:this.va}),this.va.Zr()&&z.v(z.t(z.t(z.t(n6a(this.bb,this.va.Bb(),"best"),this.Rea.bind(this,"best")),this.bAa,this),function(){this.E3.Q8&&this.Bfa()},this),z.Sw)):z.Sw("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Ca=function(){z.U(this.oa()).clear("show-other-responses");z.T.prototype.Ca.call(this)};
z.f.Rea=function(a,b){this.isActive()&&(b=b.Pe,"best"==a?(a=this.query(".js-responsesStream"),z.Yw(this,b,"add",this.Eda.bind(this,b)),this.Eda(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Xp()||0<b.Me())&&a&&(z.P(a,z.wP,{items:z.UC(b),context:2}),b=new z.sS(this.qa,b),b.Wa(a),b.zd(2),this.track(b),z.vs(this.query(".js-responsesStreamWrapper"))),this.vfa&&(a=z.sw(a),z.pw(window.document.body,0,a)))};
z.f.bAa=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Xp()?a?(this.Hc=z.QS(h6a((new z.PS(this.qa)).WL("web-inline-post-response").$L(this.va.Bb()),z.Xv(z.ni,{post:this.va,UV:!0})),this.L2).Wa(a),this.track(this.Hc)):b&&this.L2&&(a=z.rw(b),b=z.sw(b),z.pw(a,0,b)):b&&z.cd(b,"u-hide")};
z.f.Bfa=function(){this.s1||(this.s1=z.Mc(z.t(z.t(n6a(this.bb,this.va.Bb(),"other"),this.Rea.bind(this,"other")),function(){z.us(this.query(".js-showOtherResponses"));this.E3.Q8=!0},this),function(){this.s1=null},this))};z.f.Eda=function(a){(a=a.jl)&&a.next&&"other"==a.next.filter&&!this.E3.Q8&&(z.vs(this.query(".js-responsesStreamWrapper")),z.vs(this.query(".js-showOtherResponses")))};z.f.ay=function(){this.Hc&&(z.rR(this.Hc.oa(),new z.En(60,0,200,0)),this.Hc.ay())};
z.f.eya=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.ws(a)&&(z.vs(a),z.us(b),this.ay())};z.q(g8,z.Ww);g8.prototype.focus=function(){this.isActive&&this.wz.focus()};g8.prototype.close=function(){this.wz&&!this.wz.closed&&this.wz.close();this.za("close");this.fg()};g8.prototype.isActive=function(){return this.wz?!this.wz.closed:!1};g8.prototype.Va=function(){this.wz=null;g8.xa.Va.call(this)};z.f=B7a.prototype;z.f.gE=function(a,b,c){var d;d=z.im;var e=new z.mi(z.hm(d)),e=new z.Xd(e.Cl(a));d=F7(e,d);this.Tw(d);z.ux(z.XI,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.J8=function(a){var b;b=z.im;var c=new z.mi(z.hm(b));a=new z.Xd(c.la(z.sv,{catalogSlug:a.Le(),username:a.Af().Ek()}));b=F7(a,b);this.Tw(b)};z.f.K8=function(a){var b;b=z.im;var c=new z.mi(z.hm(b));a=new z.Xd(c.la(z.Fu,{sequenceSlug:a.sd()}));b=F7(a,b);this.Tw(b)};
z.f.x5=function(){var a=this.ma.la(z.oCa);return this.pa.get(a)};z.f.Tw=function(a){A7a(a,"facebook-share",{width:550,height:320})};z.q(h8,z.km);
h8.prototype.open=function(a,b){this.va=a;this.Bx=b;this.Fa=this.sG.open({bodyHtml:z.Xv(K6a,this.Bx),type:"tweet"},!0);a=this.Fa.query(".js-tweetEditor-text");b=this.qa;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.rJ=new z.AX(b,a,c(d),!0);a=new z.qX(280,!0);a.oba=C7;this.rJ.cb(a);a=t6a(G6a,this.Bx,z.im);this.rJ.hd(a);this.rJ.focus();D7a(this);z.U(this.Fa.bc).ba("remove-textshot",this.nfa.bind(this,!1),this).ba("add-textshot",this.nfa.bind(this,!0),this).ba("toggle-expand-image",this.$Ca,
this);this.Fa.subscribe(z.My,this.NDa.bind(this))};h8.prototype.NDa=function(){var a=this.rJ.hb();if(E7a(this,a)){var b=this.FP?C7a(this):null;z.v(z.t(this.pa.post(this.ma.la(z.mCa),{tweet:a,textshotInfo:b}),function(a){a=z.Yv(I6a,{id:a.value});a=z.Xv(M6a,{ZKa:a});this.ya.ua(a,{type:"success",em:1E4})},this),function(a){z.Sw(a);this.ya.ua(L6a(),"error")},this);z.fy(z.QEa,{postId:this.va.id,type:this.Bx.shareType,source:this.Bx.pKa,dest:"twitter",style:this.FP?"textshot":null});this.Fa.close()}};
h8.prototype.nfa=function(a){this.FP=a;z.od(this.Fa.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.od(this.Fa.query(".js-tweetEditor-addTextshot"),"u-hide",a)};h8.prototype.$Ca=function(){var a=this.Fa.query(".js-tweetEditor-image");z.pd(a,"tweetEditor-image--expanded")};z.f=F7a.prototype;z.f.oKa=function(a,b){var c=z.Up(),d=a.creator||{},e=m6a(b),g=l6a(b),k=u6a(a,z.im);(b=O6a(b.z5()))&&z.ee(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,QKa:e,PKa:g,shareType:"highlight",pKa:"highlight_menu"};z.v(z.t(this.qa.load("tweet-dialog"),function(b){b.open(a,l)}),z.Sw);z.fy(z.XI,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.gE=function(a,b,c,d,e){var g=z.Up().userId,k="highlight"==c?G6a:z.Gja,l=z.im,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",Rga:p.userId==g,url:u6a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):t6a(k,b,l);k=new z.Xd("https://twitter.com/intent/tweet");z.re(k,"text",d);this.Tw(k);z.ux(z.XI,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.J8=function(a){var b=z.im,c=new z.mi(z.hm(b)),c=(new z.Xd(c.la(z.sv,{catalogSlug:a.Le(),username:a.Af().Ek()}))).toString();a=z.B(""+z.Mk(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.gs({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.Xd("https://twitter.com/intent/tweet");z.re(b,"text",a);this.Tw(b)};
z.f.K8=function(a){var b=new z.mi(z.hm(z.im)),b=(new z.Xd(b.la(z.Fu,{sequenceSlug:a.sd()}))).toString();a=z.B(""+z.Mk(String(a.title))+" "+(""+b));b=new z.Xd("https://twitter.com/intent/tweet");z.re(b,"text",a);this.Tw(b)};z.f.Tw=function(a){A7a(a,"twitter-share",{width:670,height:420})};var K7a=z.Px,L7a=K7a.Da();z.Sx(L7a.scope("screen").add("quotes",R7).add("quote-responses",z7a).add("responses-stream-control",f8).add("notes-data",L7),"PostMeterBar",Q7);z.Sx(L7a.scope("app"),"PlacementsControl",P7).add("twitter",F7a).add("facebook",B7a).add("tweet-dialog",h8);z.yN(K7a,"notes");}).call(this, _mdm);
